# !/bin/bash
cat > setup.sql << EOF
CREATE DATABASE IF NOT EXISTS {DB_NAME};
CREATE USER '{USER_NAME_SQL}'@'%' IDENTIFIED BY '{USER_PSSWD_SQL}';
GRANT ALL PRIVILEGES ON {DB_NAME}.* TO '{USER_NAME_SQL}'@'%';
FLUSH PRIVILEGES;
ALTER USER '{ROOT_NAME_SQL}'@'localhost' IDENTIFIED BY '{ROOT_PSSWD_SQL}';
EOF
